### ISSUE TITLE
CSS for sort icons

### ISSUE THREAD

**Issue by steveWinter** [wedevelopnl/ux-table#10]
When setting columns as sortable an element is added to display the sort order, however there is no css included to display an icon.

**Comment by rskuipers** [comment]
This package tries to stay away from styling anything. The default SortLink component adds a `sort-asc`, `sort-desc` or `sort-none` class. We use font awesome to show an icon:


```css
.ux-table thead th .sort {
    color: #000;
    font-family: Font Awesome\ 6 Pro;
    font-style: normal;
}

.ux-table thead th .sort.sort-asc:before {
    content: "\f0de";
}

.ux-table thead th .sort.sort-desc:before {
    content: "\f0dd";
}

.ux-table thead th .sort.sort-none:before {
    content: "\f0dc";
}
```
